# Generated by Django 5.2.5 on 2025-09-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='faceapp.class'),
        ),
    ]
