# Generated by Django 5.2.5 on 2025-08-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
