# Generated by Django 5.2.5 on 2025-09-10 03:28

import faceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_alter_attendancesession_class_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=faceapp.models.get_today),
        ),
    ]
