# Generated by Django 4.2.7 on 2025-10-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_alter_attendancesession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='128D face embedding from face-api.js', null=True),
        ),
    ]
