# Generated by Django 4.2.7 on 2025-10-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_student_face_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_embedding',
        ),
        migrations.AddField(
            model_name='teacher',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
