# Generated by Django 4.2.7 on 2025-10-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_remove_student_face_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
