# Generated by Django 4.2.7 on 2025-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_student_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='DeepFace face embedding stored as JSON', null=True),
        ),
    ]
